/*
 * This file is generated by jOOQ.
 */
package com.pember.bikeshed.db.jooq;


import com.pember.bikeshed.db.jooq.tables.EventJournal;
import com.pember.bikeshed.db.jooq.tables.FlywaySchemaHistory;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EJ_OBSERVED = Internal.createIndex(DSL.name("ej_observed"), EventJournal.EVENT_JOURNAL, new OrderField[] { EventJournal.EVENT_JOURNAL.TIME_OBSERVED }, false);
    public static final Index EJ_OCCURRED = Internal.createIndex(DSL.name("ej_occurred"), EventJournal.EVENT_JOURNAL, new OrderField[] { EventJournal.EVENT_JOURNAL.TIME_OCCURRED }, false);
    public static final Index EJ_TYPE = Internal.createIndex(DSL.name("ej_type"), EventJournal.EVENT_JOURNAL, new OrderField[] { EventJournal.EVENT_JOURNAL.EVENT_TYPE }, false);
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
}
