/*
 * This file is generated by jOOQ.
 */
package com.pember.bikeshed.db.jooq;


import com.pember.bikeshed.db.jooq.tables.EventJournal;
import com.pember.bikeshed.db.jooq.tables.FlywaySchemaHistory;
import com.pember.bikeshed.db.jooq.tables.records.EventJournalRecord;
import com.pember.bikeshed.db.jooq.tables.records.FlywaySchemaHistoryRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EventJournalRecord> EVENT_JOURNAL_PKEY = Internal.createUniqueKey(EventJournal.EVENT_JOURNAL, DSL.name("event_journal_pkey"), new TableField[] { EventJournal.EVENT_JOURNAL.ENTITY_ID, EventJournal.EVENT_JOURNAL.REVISION }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
}
