/*
 * This file is generated by jOOQ.
 */
package com.pember.bikeshed.db.jooq;


import com.pember.bikeshed.db.jooq.tables.EventJournal;
import com.pember.bikeshed.db.jooq.tables.FlywaySchemaHistory;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.event_journal</code>.
     */
    public final EventJournal EVENT_JOURNAL = EventJournal.EVENT_JOURNAL;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            EventJournal.EVENT_JOURNAL,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
        );
    }
}
