/*
 * This file is generated by jOOQ.
 */
package com.pember.bikeshed.db.jooq;


import com.pember.bikeshed.db.jooq.tables.EventJournal;
import com.pember.bikeshed.db.jooq.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.event_journal</code>.
     */
    public static final EventJournal EVENT_JOURNAL = EventJournal.EVENT_JOURNAL;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
