version: "3.8"
volumes:
  ch-db:
    driver: local
services:
  db:
    image: "postgres:16.2-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bikeshed
    ports:
      - '5532:5432'
    volumes:
      - ch-db:/var/lib/postgresql/data